### ISSUE TITLE
3.0版有一个类型错误

### ISSUE THREAD

**Issue by Ockone** [bubbliiiing/faster-rcnn-pytorch#115]
```
Number of devices: 3
initialize network with normal type
Load weights model_data/voc_weights_resnet.pth.
Start Train
Epoch 1/100:   0%|                                                                                                             | 0/5805 [00:11<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "train.py", line 382, in <module>
    fit_one_epoch(model, train_util, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_d
ir)
  File "/home/turing/data1/xuezh/faster-rcnn/bubbliiiing-pytorch-3.0/utils/utils_fit.py", line 27, in fit_one_epoch
    rpn_loc, rpn_cls, roi_loc, roi_cls, total = train_util.train_step(images, boxes, labels, 1, fp16, scaler)
  File "/home/turing/data1/xuezh/faster-rcnn/bubbliiiing-pytorch-3.0/nets/frcnn_training.py", line 321, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "/home/turing/data1/xuezh/faster-rcnn/bubbliiiing-pytorch-3.0/nets/frcnn_training.py", line 290, in forward
    roi_cls_locs, roi_scores = self.model_train([base_feature, sample_rois, sample_indexes, img_size], mode = 'head')
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/turing/data1/xuezh/miniconda3/envs/frcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/turing/data1/xuezh/faster-rcnn/bubbliiiing-pytorch-3.0/nets/frcnn.py", line 104, in forward
    roi_cls_locs, roi_scores    = self.head.forward(base_feature, rois, roi_indices, img_size)
  File "/home/turing/data1/xuezh/faster-rcnn/bubbliiiing-pytorch-3.0/nets/classifier.py", line 94, in forward
    indices_and_rois = torch.cat([roi_indices[:, None], rois_feature_map], dim=1)
RuntimeError: Expected object of scalar type Long but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'
�
```
在classifier.py, line 94试图拼接roi_indices（long）和rois_feature_map（float）不同类型张量
修改classifier.py，line 88处如下，暂时解决
```
roi_indices = torch.flatten(roi_indices, 0, 1)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
roi_indices = torch.flatten(roi_indices, 0, 1).float()        #2022.4.22改错
```

**Comment by bubbliiiing** [comment]
你的版本是什么，我用1.7没错的

**Comment by bubbliiiing** [comment]
1.2也没有诶

**Comment by bubbliiiing** [comment]
重新更新了，你试试看

**Comment by Ockone** [comment]
> 

我是pytorch1.2运行的，刚刚试了一下最新的代码，没再出现这个错误
我昨天运行的v3.0 release还没结束...估摸着总共得37个小时
这其实是我第一次跑目标检测模型，不知道我的改动会不会影响精度
感谢大佬分享的代码🤩向大佬学习

**Comment by Ockone** [comment]
> 重新更新了，你试试看

我是pytorch1.2运行的，刚刚试了一下最新的代码，没再出现这个错误
我昨天运行的v3.0 release还没结束...估摸着总共得37个小时
这其实是我第一次跑目标检测模型，不知道我的改动会不会影响精度
感谢大佬分享的代码🤩向大佬学习

**Comment by bubbliiiing** [comment]
好的加油
