### ISSUE TITLE
博主，你更新后然而出错了，之前一样的操作可以运行，这是怎么回事？

### ISSUE THREAD

**Issue by Wulin824** [bubbliiiing/faster-rcnn-pytorch#12]
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) ==  np.shape(v)}
  File "train.py", line 104, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) ==  np.shape(v)}
KeyError: 'classifier.0.0.conv1.weight'

**Comment by bubbliiiing** [comment]
权重和代码都重新下
