### ISSUE TITLE
train.py训练时出现问题，rpn.py那块报出如下错误

### ISSUE THREAD

**Issue by zhenbangW** [bubbliiiing/faster-rcnn-pytorch#129]
Traceback (most recent call last):
  File "train.py", line 423, in <module>
    fit_one_epoch(model, train_util, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir)
  File "/home/bingxing2/gpuuser009/Experiment/model/Faster-RCNN_bands/utils/utils_fit.py", line 27, in fit_one_epoch
    rpn_loc, rpn_cls, roi_loc, roi_cls, total = train_util.train_step(images, boxes, labels, 1, fp16, scaler)
  File "/home/bingxing2/gpuuser009/Experiment/model/Faster-RCNN_bands/nets/frcnn_training.py", line 324, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "/home/bingxing2/gpuuser009/Experiment/model/Faster-RCNN_bands/nets/frcnn_training.py", line 287, in forward
    sample_indexes.append(torch.ones(len(sample_roi)).type_as(rpn_locs) * roi_indices[i][0])
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by bubbliiiing** [comment]
…em，只能说你改的有问题，毕竟你这个错误是一个建议框都没有……

**Comment by zhenbangW** [comment]
> …em，只能说你改的有问题，毕竟你这个错误是一个建议框都没有……

感谢您的回复，我只是想做消融实验对比一下，没有仔细阅读您的源码，我再看看

**Comment by zhenbangW** [comment]
> 0 0好的，你可以说说你改了多少

我只是改变了输入图片的通道数和大小，所有图片大小缩小为320pxl，其他的没有改变。考虑过是不是缩小输入后，主干网络输出的特征图过小以至于没有推荐框，但您代码中4次卷积缩小尺寸放大通道，320pxl应该也是可以的，还不太明白错在哪里

**Comment by bubbliiiing** [comment]
特征图过小应该还是有推荐框的，但是你的320pxl我没看懂，你设置了input_shape=[320, 320]吗

**Comment by zhenbangW** [comment]
> 特征图过小应该还是有推荐框的，但是你的320pxl我没看懂，你设置了input_shape=[320, 320]吗

嗯嗯，这个地方改了，最近没管这部分修改了。您能给个微信好友位吗？微信已提交了申请，不方便的话就算了
