### ISSUE TITLE
博主，test.py怎么没有了。之前用你的test.py跑出了这样的错误

### ISSUE THREAD

**Issue by SivenLSP** [bubbliiiing/faster-rcnn-pytorch#13]
python test.py
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    model.load_state_dict(torch.load("model_data/Epoch50-Total_Loss0.0958-Val_Loss0.1258.pth"))
  File "/home/liu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
	size mismatch for head.cls_loc.weight: copying a param with shape torch.Size([28, 4096]) from checkpoint, the shape in current model is torch.Size([84, 4096]).
	size mismatch for head.cls_loc.bias: copying a param with shape torch.Size([28]) from checkpoint, the shape in current model is torch.Size([84]).
	size mismatch for head.score.weight: copying a param with shape torch.Size([7, 4096]) from checkpoint, the shape in current model is torch.Size([21, 4096]).
	size mismatch for head.score.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([21]).

**Comment by bubbliiiing** [comment]
test.py只是我用来看网络结构的，留着没啥意义，就删了
