### ISSUE TITLE
训练自己的数据集出现了问题

### ISSUE THREAD

**Issue by xiaohan121** [bubbliiiing/faster-rcnn-pytorch#151]
Traceback (most recent call last):
  File "c:/Users/Du/Desktop/faster-rcnn-pytorch-master/faster-rcnn-pytorch-master/train_copy.py", line 439, in <module>
    fit_one_epoch(model, train_util, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir)
  File "c:\Users\Du\Desktop\faster-rcnn-pytorch-master\faster-rcnn-pytorch-master\utils\utils_fit.py", line 27, in fit_one_epoch
    rpn_loc, rpn_cls, roi_loc, roi_cls, total = train_util.train_step(images, boxes, labels, 1, fp16, scaler)
  File "c:\Users\Du\Desktop\faster-rcnn-pytorch-master\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 328, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "c:\Users\Du\Desktop\faster-rcnn-pytorch-master\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 304, in forward
    roi_loc     = roi_cls_loc[torch.arange(0, n_sample), gt_roi_label]
IndexError: index 741 is out of bounds for dimension 1 with size 4

自己的数据集是png图像和txt文件，感觉修改了dataloader也不是很麻烦，但是在训练的时候出现了如下的问题，出错的位置在gt_label出现了几百的数字，麻烦您帮忙看一下。

**Comment by bubbliiiing** [comment]
…说明你的num classes有点问题？onehot的时候出错了？
