### ISSUE TITLE
报错：RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by wyxxflwb** [bubbliiiing/faster-rcnn-pytorch#160]
开始训练后就报错了，错误部分代码如下，想听听大佬们的意见

Start Train
Epoch 1/100:   0%|                                                                                                            | 0/4137 [00:12<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "train.py", line 439, in <module>
    fit_one_epoch(model, train_util, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir)
  File "....../faster-rcnn-pytorch/utils/utils_fit.py", line 27, in fit_one_epoch
    rpn_loc, rpn_cls, roi_loc, roi_cls, total = train_util.train_step(images, boxes, labels, 1, fp16, scaler)
  File "....../faster-rcnn-pytorch/nets/frcnn_training.py", line 321, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "....../faster-rcnn-pytorch/nets/frcnn_training.py", line 243, in forward
    base_feature = self.model_train(imgs, mode = 'extractor')
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../faster-rcnn-pytorch/nets/frcnn.py", line 90, in forward
    base_feature    = self.extractor.forward(x)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "....../anaconda3/envs/frcnn/lib/python3.7/site-packages/torch/nn/functional.py", line 912, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: invalid device function

**Comment by wyxxflwb** [comment]
注：在将train.py中的CUDA赋值为False之后，训练能够进行下去

**Comment by bubbliiiing** [comment]
没有显卡？

**Comment by wyxxflwb** [comment]
有的，实验室的Ubuntu服务器，四块显卡
