### ISSUE TITLE
ValueError: optimizer got an empty parameter list 的问题

### ISSUE THREAD

**Issue by jayendsff** [bubbliiiing/faster-rcnn-pytorch#175]
您好我在用这个代码跑自己的数据集的时候遇到了这个问题，请问您有遇到过吗或者能提供一些解决的方法吗？
跑您之前其他的检测项目比如ssd/yolov4的时候没遇到过这个问题，好苦恼
Traceback (most recent call last):
  File "/home/gc/桌面/jjh/faster-rcnn-pytorch/train.py", line 364, in <module>
    'adam'  : optim.Adam(model.parameters(), Init_lr_fit, betas = (momentum, 0.999), weight_decay = weight_decay),
  File "/home/gc/anaconda3/lib/python3.9/site-packages/torch/optim/adam.py", line 74, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/home/gc/anaconda3/lib/python3.9/site-packages/torch/optim/optimizer.py", line 49, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

**Comment by jayendsff** [comment]
训练参数没有修改，后续我用Resnet就跑通了，不过没事，对了还想问问您，您的这个项目有办法画出训练过程中的P和R的曲线吗，想用在论文里

**Comment by jayendsff** [comment]
> 你的训练参数如何设置的呢

我跑了一组默认参数的epoch=330的Faster rcnn，出来结果有点奇怪，我数据集三类目标。

结果P：35%左右，R：0.85左右，F1：0.50左右，mAP：70.1

和其他算法比如ssd/yolov3、4、5的结果差异性太大，此外，训练出的权重用来检测test dataset里的图片，每张图片的目标框都达到了0.99左右，也几乎没有漏检出现，和跑出的P/mAP的数据结果对不上呀.....><不知道faster rcnn这个项目咋回事
