### ISSUE TITLE
python predict.py

### ISSUE THREAD

**Issue by MaQingya** [bubbliiiing/faster-rcnn-pytorch#22]
model_data/voc_weights_resnet.pth model, anchors, and classes loaded.
Input image filename:img/street.jpg
Traceback (most recent call last):
  File "predict.py", line 11, in <module>
    img1 = input('Input image filename:')
  File "<string>", line 1, in <module>
NameError: name 'img' is not defined

When I run the predict.py ,I faced this problem...

**Comment by bubbliiiing** [comment]
Maybe you accidentally entered an extra 1 in the code, you can download the code again, or remove the 1.

**Comment by MaQingya** [comment]
I download again，but still have the same issue. What do you mean 'an extra 1' ?

**Comment by bubbliiiing** [comment]
in the github code, the line 10 is 'img = input('Input image filename:')' , the line 11 is 'try:'. There is no 'img1 = input('Input image filename:')'
it's very strange for this problem, I think it's the edition problem.
sorry for No reply for a long time.
