### ISSUE TITLE
在训练是出现这种问题是？使用train.py出现这样的问题。

### ISSUE THREAD

**Issue by BQT11** [bubbliiiing/faster-rcnn-pytorch#33]
Epoch 1/50:   0%|          | 0/4510 [00:00<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "C:/Users/HP/Desktop/Fast_RCNNbilibili/faster-rcnn-pytorch/train.py", line 163, in <module>
    fit_ont_epoch(net,epoch,epoch_size,epoch_size_val,gen,gen_val,Freeze_Epoch,Cuda)
  File "C:/Users/HP/Desktop/Fast_RCNNbilibili/faster-rcnn-pytorch/train.py", line 27, in fit_ont_epoch
    for iteration, batch in enumerate(gen):
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)**_
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.

Original Traceback (most recent call last):
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\HP\Desktop\Fast_RCNNbilibili\faster-rcnn-pytorch\utils\dataloader.py", line 100, in __getitem__
    img,y=self.get_random_data(lines[index])
  File "C:\Users\HP\Desktop\Fast_RCNNbilibili\faster-rcnn-pytorch\utils\dataloader.py", line 30, in get_random_data
    image = Image.open(line[0])
  File "E:\PYTHON\envs\Faster_RCNN\lib\site-packages\PIL\Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP\\Desktop\\Fast'

**Comment by bubbliiiing** [comment]
注意不要用空格。

**Comment by qinghua-gui** [comment]
> 注意不要用空格。

哪儿个地方不要用空格？

**Comment by bubbliiiing** [comment]
文件夹
