### ISSUE TITLE
在get_map.py运行时出现错误

### ISSUE THREAD

**Issue by JiangZQYW** [bubbliiiing/faster-rcnn-pytorch#56]
Traceback (most recent call last):
         File "....../get_map.py", line 844, in <module>
    true_p_bar
  File "....../get_map.py", line 235, in draw_plot_func
          sorted_keys, sorted_values = zip(*sorted_dic_by_value)
ValueError: not enough values to unpack (expected 2, got 0)
非常感谢！

**Comment by bubbliiiing** [comment]
inputs有对应的txt？

**Comment by JiangZQYW** [comment]
有txt，但是input/dr文件夹下的txt内容空白，不知道怎么回事

**Comment by bubbliiiing** [comment]
应该是模型没训练好，没有预测结果，直接预测有效果？

**Comment by JiangZQYW** [comment]
直接预测也没结果。只有图片，不显示目标检测框


在2021年6月9日 ***@***.***> 写道：

应该是模型没训练好，没有预测结果，直接预测有效果？

**Comment by bubbliiiing** [comment]
根据问题汇总先排除一下，应该训练问题

**Comment by JiangZQYW** [comment]
好嘞




在2021年6月9日 ***@***.***> 写道：

根据问题汇总先排除一下，应该训练问题

**Comment by Fateeeeee** [comment]
> 好嘞 在2021年6月9日 ***@***.***> 写道： 根据问题汇总先排除一下，应该训练问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

兄弟，我也碰见全为0的情况了，你怎么解决的啊

**Comment by JiangZQYW** [comment]
这是训练跑飞了，不收敛。我加了预训练权重就能检测了。
