### ISSUE TITLE
运行train.py遇到了问题

### ISSUE THREAD

**Issue by wzp2019201645** [bubbliiiing/faster-rcnn-pytorch#86]
你好，我在训练自己的数据集之前，按照你的要求更改了相应的地方。但是当我运行train.py之后，出现了下面的bug。我看不太懂，请问这是什么原因造成的？
initialize network with normal type
Epoch 1/25:   0%|          | 0/1665 [00:00<?, ?it/s<class 'dict'>]Start Train
Epoch 1/25:   0%|          | 2/1665 [00:03<45:23,  1.64s/it, lr=0.0001, roi_cls=nan, roi_loc=nan, rpn_cls=6.98e+28, rpn_loc=5.37e+29, total_loss=nan]  C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Epoch 1/25:   0%|          | 2/1665 [00:04<57:37,  2.08s/it, lr=0.0001, roi_cls=nan, roi_loc=nan, rpn_cls=6.98e+28, rpn_loc=5.37e+29, total_loss=nan]
Traceback (most recent call last):
  File "E:/WangZhongpeng/adversarial_defence/faster-rcnn-pytorch-master/train.py", line 212, in <module>
    fit_one_epoch(model, train_util, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, end_epoch, Cuda)
  File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\utils\utils_fit.py", line 25, in fit_one_epoch
    rpn_loc, rpn_cls, roi_loc, roi_cls, total = train_util.train_step(images, boxes, labels, 1)
  File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 325, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 311, in forward
    roi_loc_loss = self._fast_rcnn_loc_loss(roi_loc, gt_roi_loc, gt_roi_label.data, self.roi_sigma)
  File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 221, in _fast_rcnn_loc_loss
    pred_loc    = pred_loc[gt_label > 0]
RuntimeError: CUDA error: device-side assert triggered

**Comment by bubbliiiing** [comment]
txt可能没改对

**Comment by bubbliiiing** [comment]
中文

**Comment by 2915482452** [comment]
> 你好，我在训练自己的数据集之前，按照你的要求更改了相应的地方。但是当我运行train.py之后，出现了下面的bug。我看不太懂，请问这是什么原因造成的？ initialize network with normal type Epoch 1/25: 0%| | 0/1665 [00:00<?, ?it/s<class 'dict'>]Start Train Epoch 1/25: 0%| | 2/1665 [00:03<45:23, 1.64s/it, lr=0.0001, roi_cls=nan, roi_loc=nan, rpn_cls=6.98e+28, rpn_loc=5.37e+29, total_loss=nan] C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed. C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed. C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed. C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed. Epoch 1/25: 0%| | 2/1665 [00:04<57:37, 2.08s/it, lr=0.0001, roi_cls=nan, roi_loc=nan, rpn_cls=6.98e+28, rpn_loc=5.37e+29, total_loss=nan] Traceback (most recent call last): File "E:/WangZhongpeng/adversarial_defence/faster-rcnn-pytorch-master/train.py", line 212, in fit_one_epoch(model, train_util, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, end_epoch, Cuda) File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\utils\utils_fit.py", line 25, in fit_one_epoch rpn_loc, rpn_cls, roi_loc, roi_cls, total = train_util.train_step(images, boxes, labels, 1) File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 325, in train_step losses = self.forward(imgs, bboxes, labels, scale) File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 311, in forward roi_loc_loss = self._fast_rcnn_loc_loss(roi_loc, gt_roi_loc, gt_roi_label.data, self.roi_sigma) File "E:\WangZhongpeng\adversarial_defence\faster-rcnn-pytorch-master\nets\frcnn_training.py", line 221, in _fast_rcnn_loc_loss pred_loc = pred_loc[gt_label > 0] RuntimeError: CUDA error: device-side assert triggered

这个问题我也遇到了，原因是annotation.txt中每个类别应该从0开始编号，在训练过程中代码写了一个label+1逻辑，将编号0留出来作为背景，所以annotation.txt应该从0开始编号，否则label+1后会有类别超出范围
