### ISSUE TITLE
测试模型出现问题？

### ISSUE THREAD

**Issue by chenshao-hua** [bubbliiiing/faster-rcnn-pytorch#89]
Traceback (most recent call last):
  File "F:/XiaoChen/Paper/MyCode/get_map.py", line 76, in <module>
    frcnn.get_map_txt(image_id, image, class_names, map_out_path)
  File "F:\XiaoChen\Paper\MyCode\frcnn.py", line 277, in get_map_txt
    roi_cls_locs, roi_scores, rois, _ = self.net(images)
  File "E:\Anaconda\anaconda\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda\anaconda\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\Anaconda\anaconda\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\XiaoChen\Paper\MyCode\nets\frcnn.py", line 83, in forward
    roi_cls_locs, roi_scores = self.head.forward(base_feature, rois, roi_indices, img_size)
  File "F:\XiaoChen\Paper\MyCode\nets\classifier.py", line 106, in forward
    roi_cls_locs = self.cls_loc(fc7)
  File "E:\Anaconda\anaconda\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda\anaconda\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "E:\Anaconda\anaconda\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

请问下模型测试出现这个问题是什么原因？model_data目录下的voc_classes.txt文件已经改为自己的数据集，而且frcnn.py文件也改了，不知道什么原因？

**Comment by bubbliiiing** [comment]
这个是cuda没用到啊，一般是环境或者显卡被占用了

**Comment by chenshao-hua** [comment]
> 这个是cuda没用到啊，一般是环境或者显卡被占用了

非常感谢，是显卡被占用的问题！
