### ISSUE TITLE
在docker上运行时，预测出现问题

### ISSUE THREAD

**Issue by zzyuyzz** [bubbliiiing/faster-rcnn-pytorch#93]
root@d0a8a33f92d2:/mnt/M/faster_rcnn# python predict.py
logs/ep100-loss0.517-val_loss0.427.pth model, anchors, and classes loaded.
Input image filename:img/test1.jpg
Traceback (most recent call last):
  File "predict.py", line 67, in <module>
    r_image = frcnn.detect_image(image)
  File "/mnt/M/faster_rcnn/frcnn.py", line 143, in detect_image
    roi_cls_locs, roi_scores, rois, _ = self.net(images)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
AssertionError
root@d0a8a33f92d2:/mnt/M/faster_rcnn# 

不知道这个是什么情况，model_path和classes_path已经按照要求换成自己的数据集的了

**Comment by bubbliiiing** [comment]
环境对吗0 0

**Comment by zzyuyzz** [comment]
> 环境对吗0 0
环境没什么问题，训练没出错，大佬你的代码我跑了faster r-cnn，yolov4和tiny，就这个出问题了。。
我搜索到的，说这个问题的原因是多核cpu训练的问题，说是：函数的返回值中有一个tensor不在gpu上，所以你找到那个tensor，使用.cuda()之后就可以了。
但是我没找到地方，因为我看前面已经使images = images.cuda()；
还是说不是这里代码的问题？
还有一个解决方法说直接换成单核gpu。

**Comment by bubbliiiing** [comment]
0 0多核还有额外的代码吗，很神奇啊

**Comment by sneakers147** [comment]
> > 环境对吗0 0
> > 环境没什么问题，训练没出错，大佬你的代码我跑了faster r-cnn，yolov4和tiny，就这个出问题了。。
> > 我搜索到的，说这个问题的原因是多核cpu训练的问题，说是：函数的返回值中有一个tensor不在gpu上，所以你找到那个tensor，使用.cuda()之后就可以了。
> > 但是我没找到地方，因为我看前面已经使images = images.cuda()；
> > 还是说不是这里代码的问题？
> > 还有一个解决方法说直接换成单核gpu。



> root@d0a8a33f92d2:/mnt/M/faster_rcnn# python predict.py logs/ep100-loss0.517-val_loss0.427.pth model, anchors, and classes loaded. Input image filename:img/test1.jpg Traceback (most recent call last): File "predict.py", line 67, in r_image = frcnn.detect_image(image) File "/mnt/M/faster_rcnn/frcnn.py", line 143, in detect_image roi_cls_locs, roi_scores, rois, _ = self.net(images) File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward return self.gather(outputs, self.output_device) File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather return gather(outputs, output_device, dim=self.dim) File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather res = gather_map(outputs) File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map return type(out)(map(gather_map, zip(*outputs))) File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map return Gather.apply(target_device, dim, *outputs) File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward assert all(map(lambda i: i.is_cuda, inputs)) AssertionError root@d0a8a33f92d2:/mnt/M/faster_rcnn#
> 
> 不知道这个是什么情况，model_path和classes_path已经按照要求换成自己的数据集的了

你好，我遇到了相同的问题。请问你解决了吗？
